[supervisord]
nodaemon=true

[program:apache]
command=apache2-foreground
autostart=true
autorestart=true

[program:websockets]
command=php artisan websockets:serve
autostart=true
autorestart=true