<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Badminton Report #{{ $matchId }} — SportSync</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;600;700&family=Barlow+Condensed:wght@400;500;600&display=swap">
    <style>
      *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: Arial, sans-serif; background: #f4f4f4; color: #111; min-height: 100vh; padding-bottom: 60px; }
      .export-bar { background: #062a78; border-bottom: 3px solid #FFE600; padding: 10px 24px; display:flex; align-items:center; gap:10px; justify-content:flex-end; position:sticky; top:0; z-index:50 }
      .bar-title { font-family: 'Oswald', sans-serif; font-size:13px; letter-spacing:1.5px; color:#FFE600; text-transform:uppercase; margin-right:auto; font-weight:700 }
      .btn-export { border: none; cursor: pointer; font-family: 'Oswald', sans-serif; font-size:12px; font-weight:700; letter-spacing:1px; padding:8px 18px; border-radius:4px; text-transform:uppercase }
      .btn-excel { background: #1e6c35; color: #fff }
      .btn-print { background: #FFE600; color: #111 }
      .container { max-width:960px; margin:0 auto; background:#fff; padding:24px 22px; border-radius:8px }
      .report-meta { margin-top:8px; color:#333; font-size:14px }
      .report-divider { border:none; border-top:2px solid #FFE600; margin:14px 0 }
      .section-title { font-weight:700; margin:12px 0 }
      table.report-table { width:100%; border-collapse:collapse }
      table.report-table th, table.report-table td { padding:8px 10px; border:1px solid #eee }
    </style>
</head>
<body>

<div class="export-bar">
  <a class="btn-export" href="{{ url('admin/badminton') }}" style="background:transparent;color:#FFE600;border:0;font-family:'Oswald',sans-serif;font-weight:700;letter-spacing:1px;text-decoration:none;margin-right:auto">&#8592; Back to Admin</a>
  <button class="btn-export btn-excel" onclick="exportExcel()">&#11015; Export Excel</button>
  <button class="btn-export btn-print" onclick="window.print()">&#128438; Print PDF</button>
  <span class="bar-title">&#127944; Badminton Report — Match #{{ $matchId }}</span>
</div>

<div class="container">

  <h1 class="report-header-title">SPORTSSYNC — BADMINTON RESULT</h1>
  <div class="report-meta">Date: {{ $exportedAt }}</div>
  @if ($committee)
    <div class="report-meta"><strong>Committee / Referee:</strong> {{ $committee }}</div>
  @endif
  <hr class="report-divider">

  <div class="section-title">Match Information</div>
  <div class="info-grid">
    <table class="report-table">
      <thead>
        <tr><th>Field</th><th>Value</th></tr>
      </thead>
      <tbody>
        <tr><td>Match ID</td><td>{{ $matchId }}</td></tr>
        <tr><td>Team A</td><td>{{ $match['team_a_name'] ?? 'Team A' }}</td></tr>
        <tr><td>Team B</td><td>{{ $match['team_b_name'] ?? 'Team B' }}</td></tr>
        <tr><td>Match Type</td><td>{{ $matchType }}</td></tr>
        <tr><td>Best Of</td><td>{{ $bestOf }}</td></tr>
        <tr><td>Status</td><td>{{ $matchStatus }}</td></tr>
        <tr><td>Overall Winner</td><td>{{ $overallWinner ?: 'TBD' }}</td></tr>
      </tbody>
    </table>
  </div>

  <div class="sets-section">
    <div class="section-title">Sets Breakdown</div>
    <table class="report-table">
      <thead>
        <tr><th>Set #</th><th>{{ $match['team_a_name'] ?? 'Team A' }}</th><th>{{ $match['team_b_name'] ?? 'Team B' }}</th><th>Timeout A</th><th>Timeout B</th><th>Serving</th><th>Winner</th></tr>
      </thead>
      <tbody>
        @foreach ($sets as $s)
          <tr>
            <td>Set {{ $s['set_number'] }}</td>
            <td class="team-a-cell">{{ (int)$s['team_a_score'] }}</td>
            <td class="team-b-cell">{{ (int)$s['team_b_score'] }}</td>
            <td>{{ (int)$s['team_a_timeout_used'] ? 'Yes' : 'No' }}</td>
            <td>{{ (int)$s['team_b_timeout_used'] ? 'Yes' : 'No' }}</td>
            <td>{{ $s['serving_team'] === 'A' ? ($match['team_a_name'] ?? 'Team A') : ($match['team_b_name'] ?? 'Team B') }}</td>
            <td>{{ $s['set_winner'] === 'A' ? ($match['team_a_name'] ?? 'Team A') : ($s['set_winner'] === 'B' ? ($match['team_b_name'] ?? 'Team B') : 'TBD') }}</td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </div>

  <div class="report-footer">Generated by SportSync</div>

</div>

<div id="match-data" data-json="{{ htmlentities(json_encode($matchData), ENT_QUOTES, 'UTF-8') }}" style="display:none"></div>
<script>
const MATCH_DATA = JSON.parse(document.getElementById('match-data').dataset.json || '{}');
function exportExcel(){ alert('Export handled by legacy client-side SheetJS in original app.'); }
</script>
</body>
</html>
